edition = "2024"
max_width = 80
unstable_features = true
use_try_shorthand = true
use_field_init_shorthand = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
overflow_delimited_expr =	true
tab_spaces = 4
newline_style = "Unix"
match_block_trailing_comma = true
hex_literal_case = "Upper"
format_strings = true
fn_single_line = true
