[package]
name = "parsec-engine-macros"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
convert_case = "0.9.0"
proc-macro-crate = "3.4.0"

[dependencies.proc-macro2]
version = "1.0"

[lib]
proc-macro = true

